name: FORCE-MAG-BUILD

on:
  workflow_dispatch: # 직접 버튼을 눌러야만 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SDK
        # 반드시 N과 P는 대문자여야 합니다!
        uses: NordicPlayground/nrf-connect-action@v2
        with:
          sdk-version: v2.5.0

      - name: Build
        run: |
          west build -b promicro_uf2/nrf52840/i2c -d build -- \
            -DCONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y \
            -DCONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n \
            -DCONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y \
            -DCONFIG_MAGNETOMETER=y \
            -DCONFIG_SLIMEVR_MAGNETOMETER=y \
            -DCONFIG_SLIMEVR_MAG_QMC6309=y \
            -DCONFIG_I2C=y \
            -DCONFIG_LSM6DSV=y

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SlimeNRF_Final_Firmware
          path: build/zephyr/zephyr.uf2
